# DISABLED: This workflow is temporarily disabled for UOS20 build testing

name: Clean Artifacts
# DISABLED: on:
# DISABLED:   schedule:
# DISABLED:     # Once a day
# DISABLED:     - cron: "0 0 * * *"
# DISABLED:   workflow_dispatch:
jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@44fc7acaf1b3d0987da0e8d4707a989d80e9554b # v1.4.0
        with:
          age: "1 week"
          skip-tags: true
          skip-recent: 5
